// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoServerApp.Data;

#nullable disable

namespace TodoServerApp.Migrations.UserDataDb
{
    [DbContext(typeof(UserDataDbContext))]
    [Migration("20241114105012_add_userdata")]
    partial class add_userdata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TodoServerApp.Data.UserElement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Patronymic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserElements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Кристина",
                            Patronymic = "Лебедь",
                            Surname = "Елена"
                        },
                        new
                        {
                            Id = 2,
                            Name = "бебе",
                            Patronymic = "бебебе",
                            Surname = "бе"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Николай",
                            Patronymic = "Васильевич",
                            Surname = "Гоголь"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
